[package]
name = "interpreter"
version = "0.1.0"
authors = ["Sniadek <karol.gruszka@dka.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
derive_more = "0.15.0"